name: Build for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Qt
      run: |
        brew install qt
        echo "$(brew --prefix qt)/bin" >> $GITHUB_PATH

    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(brew --prefix qt)

    - name: Build with CMake
      run: |
        cd build
        cmake --build .

    - name: Upload macOS Build
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: build
